<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>

		<TargetFramework>net8.0-windows</TargetFramework>

		<UseWindowsForms>true</UseWindowsForms>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>

		<RootNamespace>JustDoTheWork.Sistema</RootNamespace>
		<AssemblyName>JustDoTheWork.Sistema</AssemblyName>
		<ApplicationIcon>Icon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="Icon.ico" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\JustDoTheWork.Controller\JustDoTheWork.Controller.csproj" />
		<ProjectReference Include="..\JustDoTheWork.DTO\JustDoTheWork.DTO.csproj" />
		<ProjectReference Include="..\JustDoTheWork.Infrastructure\JustDoTheWork.Infrastructure.csproj" />
		<ProjectReference Include="..\JustDoTheWork.UI.Core\JustDoTheWork.UI.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DevExpress.Win" Version="25.2.5" />
		<PackageReference Include="DevExpress.Win.BonusSkins" Version="25.2.5" />

		<PackageReference Include="DevExpress.Win.RichEdit" Version="25.2.5" />

		<PackageReference Include="DevExpress.RichEdit.Core" Version="25.2.5" />

		<PackageReference Include="DevExpress.Win.Design" Version="25.2.5" />
	</ItemGroup>

</Project>