<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>JustDoTheWork.DTO</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JustDoTheWork.Entity\JustDoTheWork.Entity.csproj" />
  </ItemGroup>

</Project>